#pragma config(Motor,  motorA,          MA,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "event.h"

task main()
{
	eventengine_t engine;
	event_t event;

	eventengine_init(engine);
	engine.eventNone = true;
	engine.controller1 = true;
	engine.controller2 = false;

	while (true)
	{
		pollEvent(&engine, &event);
		nxtDisplayTextLine(0, "%d", event.type);
		switch (event.type)
		{
		case EVENT_TYPE_CONTROLLER_1_JOYSTICK_1_CHANGE_Y:
			motor[MA] = event.data;
			break;
		}
	}
}
