#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     IRSensor2,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          clawTop,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          clawBottom,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheels,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheels,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "util.h"

const int SPEED = 40;

void forward(float constant = 1.0)
{
	motor[leftWheels] = SPEED;
	motor[rightWheels] = SPEED;
}

void rotateLeft(float constant = 1.0)
{
	motor[leftWheels] = (float) -SPEED * constant;
	motor[rightWheels] = (float) SPEED * constant;
}

void rotateRight(float constant = 1.0)
{
	motor[leftWheels] = (float) SPEED * constant;
	motor[rightWheels] = (float) -SPEED * constant;
}

void stopMovement()
{
	motor[leftWheels] = 0;
	motor[rightWheels] = 0;
}

int getIR(int which)
{
	if (!which)
		return SensorValue[IRSensor];
	else
		return SensorValue[IRSensor2];
}

int getIRSum()
{
	return getIR(0) + getIR(1);
}

task main()
{
	{
		// Step 1: drive until perpendicular
		forward();

		while (getIR(0) != 2
			&& getIR(1) != 8) {
			;
		}

		stopMovement();
	}

	{
		// Step 2: rotate until on sum of 10 (IR)
		rotateLeft();
		while (getIRSum() != 10) {
				;
		}
		nxtDisplayTextLine(0, "IR:%d", getIRSum());
		stopMovement();
	}

	{
		// Step 3: drive and try to stay straight
	  // TODO: break when close enough for arm to do its stuff
		while (true) {
			int sum = getIRSum();

			if (sum == 10) {
				forward();
			}
			else if (sum < 10) {
				rotateLeft(0.3);
			}
			else if (sum > 10) {
				rotateRight(0.3);
			}
		}
	}
}
