//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "util.h"

task main()
{
	while(true)
	{
		nxtDisplayTextLine(0, "c1joy1v: (%d,%d)", controllerValue(1, 1, 1), controllerValue(1, 1, 2));
		nxtDisplayTextLine(1, "c1joy2v: (%d,%d)", controllerValue(1, 2, 1), controllerValue(1, 2, 2));
		nxtDisplayTextLine(2, "c2joy1v: (%d,%d)", controllerValue(2, 1, 1), controllerValue(2, 1, 2));
		nxtDisplayTextLine(3, "c2joy2v: (%d,%d)", controllerValue(2, 2, 1), controllerValue(2, 2, 2));
	}
}
