#pragma config(Sensor, S2,     HTCS2,          sensorI2CCustom)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-colour-v2.h"
#include "lib52.h"

const int BLACK_AVERAGE = 100;

task main()
{
	// Let's assume we start on black.
  // Take 25 initial readings to determine the average & highest val for black
	while (true)
	{
		int colorAverage, red, green, blue;
		HTCS2readColor(HTCS2);
		HTCS2readRawRGB(HTCS2, false, red, green, blue);
		colorAverage = (red + green + blue) / 3;

		if (colorAverage <= BLACK_AVERAGE)
			break;
		else
		{
			updateJoysticks();
			motor[motorC] = joysticks[0].y;
			motor[motorB] = joysticks[1].y;
		}
	}
}
