#pragma config(Sensor, S2,     HTCS2,          sensorI2CHiTechnicColor)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-colour-v2.h"
#include "lib52.h"

task main()
{
	while(true)
	{
		//eraseDisplay();
		updateJoysticks();
		motor[motorB] = joysticks[0].y;
		motor[motorC] = joysticks[1].y;

		int color;
		color = SensorValue[HTCS2];

		if (color == 0)
		{
			PlaySound(soundShortBlip);
		  nxtDisplayCenteredTextLine(2, "Black!");
		} else
		{
			nxtDisplayCenteredTextLine(2, "");
		}

		if (joy1Btn(CONTROLLER_A))
			PlaySound(soundShortBlip);
	}
}
