#pragma config(Sensor, S1,     accel,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lib52.h"
#include "drivers/hitechnic-accelerometer.h"

// Sensor setup
// Port 1: HiTechnic Acceleration sensor

task main()
{
	while (true)
	{
		nxtDisplayTextLine(2, "angle: %.0f", angleFromGyro(accel));
	}
}
