#pragma config(Sensor, S1,     accel,          sensorI2CHiTechnicAccel)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		int x, y, z;
		ReadSensorHTAccel
	}
}
