#pragma config(Motor,  motorB,          motorL,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorR,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "event.h"

task main()
{
	eventengine_t engine;
	event_t event;

	eventengine_init(&engine);
	engine.eventNone = true;
	engine.controller1 = true;
	engine.controller2 = false;

	while (true)
	{
		pollEvent(&engine, &event);
		nxtDisplayTextLine(0, "%d,%d", event.type, event.data);
		switch(event.type)
		{
		case EVENT_TYPE_CONTROLLER_1_JOYSTICK_1_CHANGE_Y:
			motor[motorL] = event.data;
			wait10Msec(10);
			break;
		case EVENT_TYPE_CONTROLLER_1_JOYSTICK_2_CHANGE_Y:
			motor[motorR] = event.data;
			wait10Msec(10);
			break;
		default:
			break;
		}
	}
}
