#pragma config(Sensor, S1,     ir,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		nxtDisplayBigTextLine(0, "%d", SensorValue[ir]);
	}
}
