#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ir_seeker,      sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLEFT,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRIGHT,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorARM,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    clawservo1,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    clawservo2,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*_________________________________________________________________________________________________*/
#include "JoystickDriver.c"     					// Tells ROBOTC to include the driver file for the joystick.
#include "hitechnic-accelerometer.h"			//accelerometer driver
#include "hitechnic-irseeker-v2.h" 				//ir driver
//#include "lib12.h"//
/*_________________________________________________________________________________________________*/
#define MIN_POS         0				// Minimum servo position
#define MAX_POS         180			// Maximum servo position
#define DELTA_POS       1				// Step interval
#define degreesToRadians(x) (x * PI / 180)//defined in 12Y.h
#define radiansToDegrees(x) (x *(float) 180 / PI)//defined in 12Y.h
/*_________________________________________________________________________________________________*/
/* Scale joysticks to Log for more control                                                         */
int scaleForMotor(int joyValue)							// Create some integer values
{																						// Open Bracket 1
		const int DEADZONE 			= 5;						//
		const int MAX_MOTOR_VAL = 100;					//
		const float MAX_JOY_VAL = 127.0;				//
if (abs(joyValue)<(DEADZONE))								//
		{																				// Open Bracket 2
		return 0;																// If in Dead Zone, Set to Zero
		}																				// Close Bracket 2
int direction = joyValue / abs(joyValue);		// 1 or -1 Forward or Reverse
																						// Log Joystick Value
float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
int scaledVal = (ratio * MAX_MOTOR_VAL) * direction;//
return scaledVal;
}


// See diagrams: angle = arctan(z/x),
// where gyro sensor faces up, with white part
// is furthest from locus of movement
float angleFromAccel(tSensors sensor)
{
	int x, y, z;
	float angle; // in radians
	HTACreadAllAxes(sensor, x, y, z);
	angle = atan((float) z / (float) x);
	return radiansToDegrees(angle);
}

task main()
{
// zero all motors and servos-----------------------------------------------------------------------------------
			servo[clawservo1] = 0;								//set servo to zero
			servo[clawservo2] = 0;								//set servo to zero
  		wait1Msec(1000);											//Pause to let servos move
			motor[motorLEFT] = 0;                 // Turn Motor Off
			motor[motorRIGHT] = 0;                // Turn Motor Off
     	motor[motorARM] = 0;                 	// Turn Motor Off
     	int pos = MIN_POS;

// Start the loop ----------------------------------------------------------------------------------------------
 while(true)
  {

// Right and Left Joysticks-------------------------------------------------------------------------------------
	getJoystickSettings(joystick);  					// Update Buttons and Joysticks for other functions
	motor[motorLEFT]  = scaleForMotor(joystick.joy1_y1);// MotorLEFT's powerlevel is set to the y1 stick's current position.
	motor[motorRIGHT] = scaleForMotor(joystick.joy1_y2);// MotorRIGHT's powerlevel is set to the y2 stick's current position.

//--------------------------------------------------------------------------------------------------------------
//	BUTTONS	-	COMMENT OUT UNUSED BUTTONS
			if(joy1Btn (1)== 1)      							// If Joy1-Button (1 blue X) is pressed:
	    		{
						//PlaySound(soundShortBlip);		// play the sound, 'soundshortblip'
	    		}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (2)== 1)      				// If Joy1-Button (2 green A) is pressed:
					{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
					}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (3)== 1)      				// If Joy1-Button (3 red B) is pressed:
	    		{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
	    		}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (4)== 1)      				// If Joy1-Button (4 yellow Y) is pressed:
	    		{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
					}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (5)== 1)      				// If Joy1- Left Button is pressed:
    			{
    				motor[motorARM] = 50;          // Motor is run at a power level of 100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (6)== 1)      				// If Joy1- Right Button is pressed:
		//else if (joy1Btn(6))									// this is how it was written in the sample code
				{
						pos -= DELTA_POS;								// move servo -1 step
            if (pos < MIN_POS)							// if servo is at minimum...
            {
                pos = MIN_POS;							// reset minimum position
            }
						servo[servo1] = pos;						// move servo to new position
		        servo[servo2] = pos;						// move servo to new position
    		    wait1Msec(10);									// wait for servo to move
	    		}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (7)== 1)      				// If Joy1- Left Trigger is pressed:
	    		{
						motor[motorARM] = -50;         // Motor is run at a power level of -100.
  	  			wait1Msec(10);									// Wait for motor to start
	    		}
//--------------------------------------------------------------------------------------------------------------
	    else if(joy1Btn (8)== 1)      				// If Joy1- Right Trigger is pressed:
		//else if (joy1Btn(8))									// this is how it was written in the sample code
	    		{
            pos += DELTA_POS;								// move servo 1 step
            if (pos > MAX_POS)							// if servo is at maximum...
            {
                pos = MAX_POS;							// reset maximum position
            }
            servo[servo1] = pos;						// move servo to new position
		        servo[servo2] = pos;						// move servo to new position
    		    wait1Msec(10);									// wait for servo to move
        	}
//--------------------------------------------------------------------------------------------------------------
	    else if(joystick.joy1_TopHat == 0)    // If 0 button on joy1's D-Pad (up) is pressed:
    			{
    				motor[motorARM] = 50;          // Motor is run at a power level of 100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//--------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 1)    // If 1 button on joy1's D-Pad (up right) is pressed:
    			{
    				motor[motorARM] = 50;          // Motor is run at a power level of 100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//--------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 2)    // If 2 button on joy1's D-Pad (right) is pressed:
	    		{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
	    		}
//--------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 3)    // If 3 button on joy1's D-Pad (right down) is pressed:
    			{
    				motor[motorARM] = -50;         // MotorA is run at a power level of -100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//-------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 4)    // If 4 button on joy1's D-Pad (down) is pressed:
    			{
  	  			motor[motorARM] = -50;         // MotorA is run at a power level of -100.
  	  			wait1Msec(10);									// Wait for motor to start
  	  		}
//-------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 5)    // If 5 button on joy1's D-Pad (left down) is pressed:
   				{
   	 				motor[motorARM] = -50;         // MotorA is run at a power level of -100.
    				wait1Msec(10);									// Wait for motor to start
					}
//------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 6)    // If 6 button on joy1's D-Pad (left) is pressed:
	    		{
						//PlaySound(soundShortBlip); 		// play the sound, 'soundshortblip'
	    		}
//------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 7)    // If 7 button on joy1's D-Pad (left up) is pressed:
 					{
    				motor[motorARM] = 50;          // Motor is run at a power level of 100.
    				wait1Msec(10);
    			}
//------------------------------------------------------------------------------------------------------------
    	else                            			// If Joy1-Buttons are NOT pressed:
    			{
     				motor[motorARM] = 0;           	// Turn Arm Motor Off
     				nxtDisplayTextLine(2, "angle: %.0f", angleFromAccel(accelerometer));
//						int angle = angleFromAccel(accelerometer);
//						servo[servo1] = (0 + angle);//servo value based on sensor
//						servo[servo2] = (0 + angle);//servo value based on sensor


//     				readAccel(accelerometer);
//     				if(accelerometer.x>0)												// TEMP CODE read sensor
//		      																							// TEMP CODE formula for angle
//         		servo[servo1] = pos + DELTA_POS;						// TEMP CODE move servo to new position
//		        servo[servo2] = pos + DELTA_POS;						// TEMP CODE move servo to new position


    			}
//-----------------------------------------------------------------------------------------------------------------
  }	// End While Loop ---------------------------------------------------------------------------------------------
}   // End Task Main ----------------------------------------------------------------------------------------------


/*to do list
accel sensor servo arm
ir sensor
Lift arm encoder
preset arm heights
*/
