#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     ir_seeker,      sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,          motorLEFT,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorRIGHT,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorARM,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    clawservo1,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    clawservo2,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"     					// Tells ROBOTC to include the driver file for the joystick.
#include "hitechnic-accelerometer.h"			//accelerometer driver
#include "hitechnic-irseeker-v2.h" 				//ir driver
#include "lib12.h"

#define MIN_POS         0				// Minimum servo position
#define MAX_POS         180			// Maximum servo position
#define DELTA_POS       1				// Step interval
//#define degreesToRadians(x) (x * PI / 180)
//#define radiansToDegrees(x) (x *(float) 180 / PI)



task main()
{
// zero all motors and servos-----------------------------------------------------------------------------------
			servo[clawservo1] = 0;								//set servo to zero
			servo[clawservo2] = 0;								//set servo to zero
  		wait1Msec(1000);											//Pause to let servos move
			motor[motorLEFT] = 0;                 // Turn Motor Off
			motor[motorRIGHT] = 0;                // Turn Motor Off
     	motor[motorARM] = 0;                 	// Turn Motor Off
     	int pos = MIN_POS;


//     	accelData accelerometer;
//   		accelStart(S4);


// Start the loop ----------------------------------------------------------------------------------------------
 while(true)
  {

// Right and Left Joysticks-------------------------------------------------------------------------------------

// You can translate the full range of the joystick y-axis to servo angle by the following code.
// servo[servo1] = ((joystick.joy1_y1 + 128)*180)/256;
// servo[servo1] = ((joystick.joy1_y2 + 128)*180)/256;

// You can translate the full range of the joystick y-axis to Motor power by the following code.
// motor[motorA] = joystick.joy1_y1;				// MotorA's powerlevel is set to the y1 stick's current position.
// motor[motorB] = joystick.joy1_y2;				// MotorB's powerlevel is set to the y2 stick's current position.

	motor[motorLEFT] = joystick.joy1_y1;			// MotorLEFT's powerlevel is set to the y1 stick's current position.
	motor[motorRIGHT] = joystick.joy1_y2;			// MotorRIGHT's powerlevel is set to the y2 stick's current position.
	getJoystickSettings(joystick);  					// Update Buttons and Joysticks for other functions
//--------------------------------------------------------------------------------------------------------------
//	BUTTONS	-	COMMENT OUT UNUSED BUTTONS
			if(joy1Btn (1)== 1)      							// If Joy1-Button (1 blue X) is pressed:
	    		{
						//PlaySound(soundShortBlip);		// play the sound, 'soundshortblip'
	    		}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (2)== 1)      				// If Joy1-Button (2 green A) is pressed:
					{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
					}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (3)== 1)      				// If Joy1-Button (3 red B) is pressed:
	    		{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
	    		}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (4)== 1)      				// If Joy1-Button (4 yellow Y) is pressed:
	    		{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
					}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (5)== 1)      				// If Joy1- Left Button is pressed:
    			{
    				motor[motorARM] = 100;          // Motor is run at a power level of 100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (6)== 1)      				// If Joy1- Right Button is pressed:
		//else if (joy1Btn(6))									// this is how it was written in the sample code

        	{
						pos -= DELTA_POS;								// move servo -1 step
            if (pos < MIN_POS)							// if servo is at minimum...
            {
                pos = MIN_POS;							// reset minimum position
            }
						servo[servo1] = pos;						// move servo to new position
		        servo[servo2] = pos;						// move servo to new position
    		    wait1Msec(10);									// wait for servo to move
	    		}

//--------------------------------------------------------------------------------------------------------------
			else if(joy1Btn (7)== 1)      				// If Joy1- Left Trigger is pressed:
	    		{
						motor[motorARM] = -100;         // Motor is run at a power level of -100.
  	  			wait1Msec(10);									// Wait for motor to start
	    		}
//--------------------------------------------------------------------------------------------------------------
	    else if(joy1Btn (8)== 1)      				// If Joy1- Right Trigger is pressed:
		//else if (joy1Btn(8))									// this is how it was written in the sample code
	    		{
            pos += DELTA_POS;								// move servo 1 step
            if (pos > MAX_POS)							// if servo is at maximum...
            {
                pos = MAX_POS;							// reset maximum position
            }
            servo[servo1] = pos;						// move servo to new position
		        servo[servo2] = pos;						// move servo to new position
    		    wait1Msec(10);									// wait for servo to move
        	}
//--------------------------------------------------------------------------------------------------------------
	    else if(joystick.joy1_TopHat == 0)    // If 0 button on joy1's D-Pad (up) is pressed:
    			{
    				motor[motorARM] = 100;          // Motor is run at a power level of 100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//--------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 1)    // If 1 button on joy1's D-Pad (up right) is pressed:
    			{
    				motor[motorARM] = 100;          // Motor is run at a power level of 100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//--------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 2)    // If 2 button on joy1's D-Pad (right) is pressed:
	    		{
						//PlaySound(soundShortBlip);  	// play the sound, 'soundshortblip'
	    		}
//--------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 3)    // If 3 button on joy1's D-Pad (right down) is pressed:
    			{
    				motor[motorARM] = -100;         // MotorA is run at a power level of -100.
    				wait1Msec(10);									// Wait for motor to start
    			}
//-------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 4)    // If 4 button on joy1's D-Pad (down) is pressed:
    			{
  	  			motor[motorARM] = -100;         // MotorA is run at a power level of -100.
  	  			wait1Msec(10);									// Wait for motor to start
  	  		}
//-------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 5)    // If 5 button on joy1's D-Pad (left down) is pressed:
   				{
   	 				motor[motorARM] = -100;         // MotorA is run at a power level of -100.
    				wait1Msec(10);									// Wait for motor to start
					}
//------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 6)    // If 6 button on joy1's D-Pad (left) is pressed:
	    		{
						//PlaySound(soundShortBlip); 		// play the sound, 'soundshortblip'
	    		}
//------------------------------------------------------------------------------------------------------------
			else if(joystick.joy1_TopHat == 7)    // If 7 button on joy1's D-Pad (left up) is pressed:
 					{
    				motor[motorARM] = 100;          // Motor is run at a power level of 100.
    				wait1Msec(10);
    			}
//------------------------------------------------------------------------------------------------------------
    	else                            			// If Joy1-Buttons are NOT pressed:
    			{
     				motor[motorLEFT] = 0;           // Turn Left Motor Off
						motor[motorRIGHT] = 0;          // Turn Right Motor Off
     				motor[motorARM] = 0;           	// Turn Arm Motor Off
     				nxtDisplayTextLine(2, "angle: %.0f", angleFromAccel(accelerometer));
						int angle = angleFromAccel(accelerometer);
						servo[servo1] = (0 + angle);//servo value based on sensor
						servo[servo2] = (0 + angle);//servo value based on sensor


//     				readAccel(accelerometer);
//     				if(accelerometer.x>0)												// TEMP CODE read sensor
//		      																							// TEMP CODE formula for angle
//         		servo[servo1] = pos + DELTA_POS;						// TEMP CODE move servo to new position
//		        servo[servo2] = pos + DELTA_POS;						// TEMP CODE move servo to new position


    			}
//-----------------------------------------------------------------------------------------------------------------
  }	// End While Loop ---------------------------------------------------------------------------------------------
}   // End Task Main ----------------------------------------------------------------------------------------------


/*to do list
add deadband to joystick
logrithmic drive control
accel sensor
brake on arm lift
ir sensor
*/
